name: 部署文档

on:
  push:
    branches:
      - master

jobs:
  depoly-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Deps
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - uses: actions/cache@v3
        id: node-modules
        with:
          path: node-modules/
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Build Docs
        env:
          NODE-OPTIONS: --max_old_space_size=8192
        run: yarn run docs:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: blog
          folder: docs/.vuepress/dist
          token: ${{ secrets.ACCESS_TOKEN }}